site_name: evcastelani
nav:
      - Home: index.md
      - Escritos: escritos.md 
      - Projetos: projetos.md  
      - CV: cv.md 
      - Agenda: agenda.md  
extra_javascript: 
            - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
            - mdx_math

theme:
     name: 'material'

